import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Weekly AI Reports | rAsh Score',
  description: 'Automated weekly blog posts summarizing the state of AI brand visibility in India, generated by LLMs.',
};

export default function ReportsLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
