"use client";

import { useState } from "react";
import BrandInput from "@/components/BrandInput";
import LLMOScore from "@/components/LLMOScore";
import AIResponse from "@/components/AIResponse";
import ModelComparison from "@/components/ModelComparison";
import CompetitorComparison from "@/components/CompetitorComparison";
import { SkeletonResults } from "@/components/LoadingSkeleton";
import { useToast } from "@/components/Toast";
import { AnimatedCard, AnimatedSection } from "@/components/AnimatedCard";

export interface BrandCheckResult {
    brand: string;
    category: string;
    score: number;
    responses: {
        model: string;
        modelType: "free" | "pro";
        text: string;
        sentiment: "positive" | "neutral" | "negative";
        mentionsCount: number;
    }[];
    breakdown: {
        recommendation: number;
        sentiment: number;
        prominence: number;
        accuracy: number;
    };
    tips: string[];
    source?: "database" | "ai";
    meta?: {
        responseTime: number;
        modelsQueried: number;
        timestamp: string;
        source?: "database" | "ai";
    };
}

export default function Home() {
    const [result, setResult] = useState<BrandCheckResult | null>(null);
    const [loading, setLoading] = useState(false);
    const [competitor, setCompetitor] = useState<BrandCheckResult | null>(null);
    const [competitorLoading, setCompetitorLoading] = useState(false);
    const [showAIResponsesModal, setShowAIResponsesModal] = useState(false);
    const { addToast } = useToast();

    const handleBrandCheck = async (brand: string, category: string = "general") => {
        setLoading(true);
        setResult(null);
        setCompetitor(null);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ brand, category }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze brand");
            }

            setResult(data);
            const source = data.source || data.meta?.source;
            if (source === "database") {
                addToast(`Found ${brand} in database — instant results!`, "success");
            } else {
                addToast(`AI analysis complete for ${brand}! Saved for next time.`, "success");
            }
        } catch (error) {
            console.error("Error checking brand:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze brand. Please try again.",
                "error"
            );
        } finally {
            setLoading(false);
        }
    };

    const handleCompetitorCheck = async (competitorBrand: string) => {
        if (!result) return;

        if (competitorBrand.trim().toLowerCase() === result.brand.trim().toLowerCase()) {
            addToast("Cannot compare a brand with itself!", "error");
            return;
        }

        setCompetitorLoading(true);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    brand: competitorBrand,
                    category: result.category
                }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze competitor");
            }

            setCompetitor(data);
            addToast(`Competitor analysis complete!`, "success");
        } catch (error) {
            console.error("Error checking competitor:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze competitor. Please try again.",
                "error"
            );
        } finally {
            setCompetitorLoading(false);
        }
    };

    const handleCopyResults = async () => {
        if (!result) return;

        const summary = `
rAsh Score Report for ${result.brand}
=========================================
rAsh Score: ${result.score}/100

Breakdown:
- Recommendation: ${result.breakdown.recommendation}/40
- Sentiment: ${result.breakdown.sentiment}/30
- Prominence: ${result.breakdown.prominence}/20
- Accuracy: ${result.breakdown.accuracy}/10

Tips:
${result.tips.map((tip, i) => `${i + 1}. ${tip}`).join("\n")}

Generated by rAsh Score (https://rashscore.live)
        `.trim();

        try {
            await navigator.clipboard.writeText(summary);
            addToast("Results copied to clipboard!", "success");
        } catch {
            addToast("Failed to copy results", "error");
        }
    };

    return (
        <div className="rs-page relative overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
            <div className="absolute -top-24 left-1/2 h-[420px] w-[720px] -translate-x-1/2 rounded-full bg-indigo-500/[0.05] blur-[140px] pointer-events-none" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-14 relative z-10">
                {/* Hero Section */}
                <section className="grid items-center gap-8 sm:gap-10 lg:grid-cols-[1.05fr_0.95fr] mb-10 sm:mb-16 relative">
                    <div className="text-left">
                        <div className="rs-badge mb-5 cursor-default">
                            <span className="rs-badge-dot" />
                            AI brand visibility intelligence
                        </div>
                        <h1 className="text-3xl sm:text-5xl md:text-6xl font-semibold mb-5 tracking-[-0.04em] leading-[1.02] text-white text-balance">
                            Understand how AI systems <span className="gradient-text">see your brand.</span>
                        </h1>
                        <p className="text-base sm:text-lg max-w-2xl mb-7 leading-7 sm:leading-8 text-balance" style={{ color: 'var(--rs-text-secondary)' }}>
                            Measure brand visibility across AI recommendations, benchmark competitors, and get prioritized actions for improving discoverability.
                        </p>
                        <div className="grid grid-cols-1 gap-3 max-w-xl sm:grid-cols-3 text-left">
                            {[
                                ['4', 'visibility dimensions'],
                                ['285', 'tracked brands'],
                                ['19', 'industry cohorts'],
                            ].map(([value, label]) => (
                                <div key={label} className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4">
                                    <div className="text-2xl font-semibold text-white">{value}</div>
                                    <div className="mt-1 text-xs uppercase tracking-[0.16em]" style={{ color: 'var(--rs-text-muted)' }}>{label}</div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="rounded-[1.5rem] sm:rounded-[1.75rem] border border-white/[0.08] bg-[#16181d]/80 p-4 sm:p-6 shadow-2xl shadow-black/20 backdrop-blur-md">
                        <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-b border-white/[0.06] pb-4">
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-[0.18em]" style={{ color: 'var(--rs-text-muted)' }}>Run an audit</p>
                                <h2 className="mt-1 text-xl font-semibold text-white">Check brand visibility</h2>
                            </div>
                            <span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-300">Live</span>
                        </div>
                        <BrandInput onSubmit={handleBrandCheck} loading={loading} />
                    </div>
                </section>

                {/* Featured Video Section */}
                <section className="mb-10 sm:mb-12 animate-slide-up">
                    <div className="rs-card p-4 sm:p-8 rounded-2xl overflow-hidden relative group border border-white/[0.08] bg-[#16181d]/70 backdrop-blur-md">
                        <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 via-transparent to-purple-500/5 pointer-events-none" />
                        <div className="relative z-10 flex flex-col md:flex-row items-stretch md:items-center gap-6 sm:gap-8">
                            <div className="w-full md:w-1/2 rounded-xl overflow-hidden border border-white/[0.08] shadow-2xl bg-black/60 group-hover:border-indigo-500/30 transition-all duration-500">
                                <video 
                                    src="/videos/latest_report_intro.mp4" 
                                    controls 
                                    preload="metadata"
                                    className="w-full h-auto aspect-video object-cover"
                                >
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                            <div className="w-full md:w-1/2 text-left">
                                <div className="rs-badge mb-4 inline-flex items-center gap-2 border-purple-500/20 bg-purple-500/10 text-purple-400">
                                    <span className="rs-badge-dot bg-purple-400" />
                                    Latest intelligence brief
                                </div>
                                <h2 className="text-2xl sm:text-3xl font-extrabold mb-4 text-white tracking-tight">Weekly market brief</h2>
                                <p style={{ color: 'var(--rs-text-secondary)' }} className="mb-6 leading-relaxed text-sm sm:text-base">
                                    Review the latest summary of category movement, visibility shifts, and brands gaining share in AI recommendations.
                                </p>
                                <a href="/reports" className="text-indigo-400 hover:text-indigo-300 font-bold inline-flex items-center gap-2 transition-all group/link">
                                    View reports <span className="group-hover/link:translate-x-1 transition-transform">→</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </section>

            {/* Loading State with Skeleton */}
            {loading && <SkeletonResults />}

            {/* Results Section */}
            {result && !loading && (
                <div className="space-y-8">
                    {/* Copy Button */}
                    <div className="flex justify-end">
                        <button
                            onClick={handleCopyResults}
                            className="btn-secondary flex items-center gap-2"
                            aria-label="Copy results to clipboard"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                            </svg>
                            Copy Results
                        </button>
                    </div>

                    {/* Score and Summary */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        <AnimatedCard delay={0.1}>
                            <LLMOScore score={result.score} breakdown={result.breakdown} />
                        </AnimatedCard>

                        <AnimatedCard delay={0.2} className="lg:col-span-2 rs-card p-6">
                            <h3 className="text-lg font-semibold mb-4">
                                📊 AI Analysis for <span className="text-primary-400">{result.brand}</span>
                            </h3>
                            <div className="space-y-4">
                                {result.tips.map((tip, index) => (
                                    <div key={index} className="flex items-start gap-3">
                                        <div className="w-6 h-6 rounded-full bg-primary-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                                            <span className="text-primary-400 text-sm">💡</span>
                                        </div>
                                        <p style={{ color: 'var(--rs-text-secondary)' }}>{tip}</p>
                                    </div>
                                ))}
                            </div>
                            {result.meta && (
                                <div className="flex items-center gap-2 mt-4">
                                    {(result.source === "database" || result.meta.source === "database") ? (
                                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[11px] text-emerald-400 font-medium">
                                            <span>📦</span> From Database · Instant
                                        </span>
                                    ) : (
                                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-[11px] text-purple-400 font-medium">
                                            <span>🤖</span> Live AI Analysis · {result.meta.responseTime}ms
                                        </span>
                                    )}
                                    <span className="text-xs" style={{ color: 'var(--rs-text-muted)' }}>
                                        {result.meta.modelsQueried} model{result.meta.modelsQueried !== 1 ? 's' : ''}
                                    </span>
                                </div>
                            )}
                        </AnimatedCard>
                    </div>

                    {/* Model Comparison */}
                    <AnimatedSection delay={0.3}>
                        <ModelComparison responses={result.responses} brand={result.brand} />
                    </AnimatedSection>

                    {/* View AI Responses Button */}
                    <AnimatedSection delay={0.4}>
                        <button
                            onClick={() => setShowAIResponsesModal(true)}
                            className="w-full px-6 py-3 rounded-lg font-medium transition-all flex items-center justify-center gap-2 rs-card hover:border-primary-500/30"
                        >
                            <span>🤖</span>
                            <span>View Detailed AI Responses</span>
                            <span style={{ color: 'var(--rs-text-muted)' }}>({result.responses.length} models)</span>
                        </button>
                    </AnimatedSection>

                    {/* Competitor Comparison */}
                    <AnimatedSection delay={0.6}>
                        <CompetitorComparison
                            brandResult={result}
                            competitorResult={competitor}
                            onCompare={handleCompetitorCheck}
                            loading={competitorLoading}
                        />
                    </AnimatedSection>
                </div>
            )}

            {/* Features Section */}
            {!result && !loading && (
                <section id="features" className="mt-20 animate-slide-up" aria-labelledby="features-heading">
                    <div className="text-center mb-10">
                        <h2 id="features-heading" className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">Why rAsh Score?</h2>
                        <div className="w-12 h-1 bg-indigo-500 mx-auto mt-3 rounded-full" />
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 sm:gap-8">
                        <article className="rs-card p-6 sm:p-8 text-center bg-[#16181d]/40 backdrop-blur-sm border-white/[0.06] hover:border-indigo-500/20">
                            <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center mx-auto mb-5 text-indigo-400 font-bold border border-indigo-500/20">
                                🔍
                            </div>
                            <h3 className="font-bold text-lg text-white mb-3">Multi-Model Analysis</h3>
                            <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>Check what OpenAI, Gemini, NVIDIA, and Groq AI models say about your brand in real-time.</p>
                        </article>
                        <article className="rs-card p-6 sm:p-8 text-center bg-[#16181d]/40 backdrop-blur-sm border-white/[0.06] hover:border-purple-500/20">
                            <div className="w-12 h-12 rounded-2xl bg-purple-500/10 flex items-center justify-center mx-auto mb-5 text-purple-400 font-bold border border-purple-500/20">
                                📊
                            </div>
                            <h3 className="font-bold text-lg text-white mb-3">rAsh Score</h3>
                            <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>Get a single 0-100 score measuring your brand&apos;s AI visibility, recommendation tier, and sentiment.</p>
                        </article>
                        <article className="rs-card p-6 sm:p-8 text-center bg-[#16181d]/40 backdrop-blur-sm border-white/[0.06] hover:border-pink-500/20">
                            <div className="w-12 h-12 rounded-2xl bg-pink-500/10 flex items-center justify-center mx-auto mb-5 text-pink-400 font-bold border border-pink-500/20">
                                ⚔️
                            </div>
                            <h3 className="font-bold text-lg text-white mb-3">Competitor Analysis</h3>
                            <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>Directly run comparative query lookups and discover gaps in your AI search share of voice.</p>
                        </article>
                    </div>
                </section>
            )}

            {/* How It Works */}
            {!result && !loading && (
                <section id="how-it-works" className="mt-20 animate-slide-up" aria-labelledby="how-it-works-heading">
                    <div className="text-center mb-10">
                        <h2 id="how-it-works-heading" className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">How It Works</h2>
                        <div className="w-12 h-1 bg-purple-500 mx-auto mt-3 rounded-full" />
                    </div>
                    <div className="flex flex-col md:flex-row items-stretch justify-center gap-6 max-w-4xl mx-auto px-4">
                        <div className="flex-1 rs-card p-6 border-white/[0.06] bg-[#16181d]/30 text-center flex flex-col items-center">
                            <div className="w-10 h-10 rounded-full bg-indigo-500/20 border border-indigo-500/40 text-indigo-300 flex items-center justify-center font-bold text-sm mb-4">1</div>
                            <h4 className="text-white font-bold text-base mb-2">Identify Brand</h4>
                            <span className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>Enter your brand name and target industry sector</span>
                        </div>
                        <div className="hidden md:flex items-center text-slate-600 font-black text-xl">→</div>
                        <div className="flex-1 rs-card p-6 border-white/[0.06] bg-[#16181d]/30 text-center flex flex-col items-center">
                            <div className="w-10 h-10 rounded-full bg-purple-500/20 border border-purple-500/40 text-purple-300 flex items-center justify-center font-bold text-sm mb-4">2</div>
                            <h4 className="text-white font-bold text-base mb-2">Query Engines</h4>
                            <span className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>We trigger queries across 6 leading LLM architectures</span>
                        </div>
                        <div className="hidden md:flex items-center text-slate-600 font-black text-xl">→</div>
                        <div className="flex-1 rs-card p-6 border-white/[0.06] bg-[#16181d]/30 text-center flex flex-col items-center">
                            <div className="w-10 h-10 rounded-full bg-pink-500/20 border border-pink-500/40 text-pink-300 flex items-center justify-center font-bold text-sm mb-4">3</div>
                            <h4 className="text-white font-bold text-base mb-2">Analyze visibility</h4>
                            <span className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>Get the breakdown, recommendations & action steps</span>
                        </div>
                    </div>
                </section>
            )}

            {/* What's in the Name? - Story Section */}
            {!result && !loading && (
                <section className="mt-20 max-w-4xl mx-auto animate-slide-up" aria-labelledby="name-story-heading">
                    <div className="text-center mb-10">
                        <h2 id="name-story-heading" className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                            What&apos;s in the Name? <span className="inline-block animate-pulse text-amber-500">🔥</span>
                        </h2>
                        <p className="text-sm mt-2" style={{ color: 'var(--rs-text-muted)' }}>
                            Every great tool has a story. Here&apos;s ours.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 px-4">
                        {/* The rAsh Story */}
                        <div className="relative overflow-hidden rounded-2xl border border-white/[0.06] bg-[#16181d]/40 p-6 sm:p-8 hover:border-indigo-500/20 transition-all duration-300">
                            <div className="absolute -right-4 -top-4 text-[90px] font-black opacity-[0.03] text-indigo-500 select-none pointer-events-none">r</div>
                            <div className="text-3xl mb-4">👨‍💻</div>
                            <h3 className="text-lg font-bold text-white mb-3">
                                <span className="text-indigo-400 font-extrabold">r</span><span className="text-purple-400 font-extrabold">A</span><span className="text-pink-400 font-extrabold">sh</span> = P<span className="text-indigo-400 font-black underline decoration-indigo-500/30 underline-offset-4">rash</span>anth
                            </h3>
                            <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                                The name comes from the creator — <strong style={{ color: 'var(--rs-text-primary)' }}>Prashanth Kumar</strong>. 
                                Hidden in plain sight: p<strong className="text-indigo-400">rash</strong>anth → <strong className="text-purple-400">rAsh</strong>. 
                                A personal signature baked into every scoring run. 
                            </p>
                            <p className="text-xs mt-4 italic font-medium" style={{ color: 'var(--rs-text-muted)' }}>
                                &quot;I wanted the tool to carry a piece of me — so I hid my name in it.&quot;
                            </p>
                        </div>

                        {/* The Ash Warning */}
                        <div className="relative overflow-hidden rounded-2xl border border-white/[0.06] bg-[#16181d]/40 p-6 sm:p-8 hover:border-orange-500/20 transition-all duration-300">
                            <div className="absolute -right-4 -top-4 text-[90px] font-black opacity-[0.03] text-orange-500 select-none pointer-events-none">🔥</div>
                            <div className="text-3xl mb-4">💀</div>
                            <h3 className="text-lg font-bold text-white mb-3">
                                Ignore AI? Your brand turns to <span className="text-orange-400 font-black">Ash</span>.
                            </h3>
                            <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                                The dual metaphor warning: <strong className="text-orange-300">Ash</strong> is what remains 
                                when something burns out. If you&apos;re not visible in AI search recommendations, 
                                your brand is slowly turning to ash — invisible and irrelevant.
                            </p>
                            <p className="text-xs mt-4 italic font-medium" style={{ color: 'var(--rs-text-muted)' }}>
                                &quot;Don&apos;t let your brand become ash. Check your rAsh Score.&quot;
                            </p>
                        </div>
                    </div>

                    {/* Fun pronunciation guide */}
                    <div className="mt-8 text-center px-4">
                        <div className="inline-flex items-center gap-3 px-5 py-3 rounded-full bg-white/[0.02] border border-white/[0.06]">
                            <span className="text-xs" style={{ color: 'var(--rs-text-muted)' }}>Pronunciation:</span>
                            <span className="text-white font-mono text-sm font-bold tracking-wider">/ræʃ skɔːr/</span>
                            <span className="text-xs" style={{ color: 'var(--rs-text-muted)' }}>— sounds like &quot;rash score&quot;</span>
                            <span className="text-lg">😏</span>
                        </div>
                    </div>
                </section>
            )}

            {/* Why It Matters */}
            {!result && !loading && (
                <section className="mt-20 max-w-4xl mx-auto animate-slide-up" aria-labelledby="why-matters-heading">
                    <div className="text-center mb-10">
                        <h2 id="why-matters-heading" className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                            Why Your rAsh Score Matters
                        </h2>
                        <div className="w-12 h-1 bg-pink-500 mx-auto mt-3 rounded-full" />
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 px-4">
                        <div className="rs-card p-6 text-center group bg-[#16181d]/30 border-white/[0.06] hover:border-indigo-500/20">
                            <div className="text-3xl sm:text-4xl font-black text-indigo-400 mb-2 transition-transform group-hover:scale-110 duration-300">40%</div>
                            <p className="text-xs sm:text-sm font-medium" style={{ color: 'var(--rs-text-secondary)' }}>of users prefer asking AI over search engines for product lookups</p>
                        </div>
                        <div className="rs-card p-6 text-center group bg-[#16181d]/30 border-white/[0.06] hover:border-purple-500/20">
                            <div className="text-3xl sm:text-4xl font-black text-purple-400 mb-2 transition-transform group-hover:scale-110 duration-300">Zero</div>
                            <p className="text-xs sm:text-sm font-medium" style={{ color: 'var(--rs-text-secondary)' }}>clicks needed — AI answers the query directly without visiting external links</p>
                        </div>
                        <div className="rs-card p-6 text-center group bg-[#16181d]/30 border-white/[0.06] hover:border-pink-500/20">
                            <div className="text-3xl sm:text-4xl font-black text-pink-400 mb-2 transition-transform group-hover:scale-110 duration-300">1st</div>
                            <p className="text-xs sm:text-sm font-medium" style={{ color: 'var(--rs-text-secondary)' }}>brand AI recommends gets the lead. There is no second page in AI replies</p>
                        </div>
                    </div>

                    <div className="mt-8 mx-4 p-5 rounded-2xl bg-white/[0.02] border border-white/[0.06] text-center backdrop-blur-sm">
                        <p className="text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                            <strong className="text-white">Traditional SEO is built for Google crawlers.</strong> rAsh Score is engineered for the AI-first age.{" "}
                            <span style={{ color: 'var(--rs-text-muted)' }}>When a consumer asks Claude or Gemini for recommendations, you want your brand in the final response.</span>
                        </p>
                    </div>
                </section>
            )}

            {/* FAQ Section */}
            {!result && !loading && (
                <section id="faq" className="mt-20 max-w-4xl mx-auto animate-slide-up" aria-labelledby="faq-heading">
                    <div className="text-center mb-10">
                        <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">Frequently Asked Questions</h2>
                        <div className="w-12 h-1 bg-indigo-500 mx-auto mt-3 rounded-full" />
                    </div>
                    <div className="space-y-4 px-4">
                        <div className="rs-card p-6 border-l-4 border-l-indigo-500 bg-[#16181d]/40 border-white/[0.06]">
                            <h3 className="text-base sm:text-lg font-bold text-white mb-2">Why &quot;rAsh&quot; and not something corporate?</h3>
                            <p className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                                Because we believe utility tools should have character. <strong className="text-indigo-300">rAsh</strong> carries the signature of Prashanth Kumar, and acts as a reminder: ignore your AI presence, and your brand visibility turns to <strong className="text-orange-400 font-bold">ash</strong>.
                            </p>
                        </div>
                        <div className="rs-card p-6 border-l-4 border-l-purple-500 bg-[#16181d]/40 border-white/[0.06]">
                            <h3 className="text-base sm:text-lg font-bold text-white mb-2">How is the rAsh Score calculated?</h3>
                            <p className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                                The score is out of 100, composed of: <strong>Recommendation (40 points)</strong>, <strong>Sentiment (30 points)</strong>, <strong>Prominence (20 points)</strong>, and <strong>Accuracy (10 points)</strong>. We query 6 models (OpenAI, Gemini, Groq, NVIDIA) to build the aggregate view.
                            </p>
                        </div>
                        <div className="rs-card p-6 border-l-4 border-l-pink-500 bg-[#16181d]/40 border-white/[0.06]">
                            <h3 className="text-base sm:text-lg font-bold text-white mb-2">Why might my score vary?</h3>
                            <p className="text-xs sm:text-sm leading-relaxed" style={{ color: 'var(--rs-text-secondary)' }}>
                                LLMs are non-deterministic, generating slightly varied outputs per run. Standardized system prompting is applied to keep score variance minimal.
                            </p>
                        </div>
                    </div>
                </section>
            )}

            {/* AI Responses Slide-out Panel */}
            {showAIResponsesModal && result && (
                <div className="fixed inset-0 z-50 flex justify-end">
                    {/* Backdrop */}
                    <div
                        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                        onClick={() => setShowAIResponsesModal(false)}
                    />

                    {/* Slide-out Panel */}
                    <div className="relative w-full max-w-2xl border-l 
                                    shadow-2xl overflow-y-auto animate-slide-in" style={{ background: 'var(--rs-bg-surface)', borderColor: 'var(--rs-border)' }}>
                        {/* Header */}
                        <div className="sticky top-0 border-b p-4 flex items-center justify-between" style={{ background: 'var(--rs-bg-surface)', borderColor: 'var(--rs-border)' }}>
                            <h2 className="text-xl font-semibold flex items-center gap-2">
                                <span>🤖</span>
                                Detailed AI Responses
                            </h2>
                            <button
                                onClick={() => setShowAIResponsesModal(false)}
                                className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
                                aria-label="Close panel"
                            >
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>

                        {/* Content */}
                        <div className="p-4 space-y-4">
                            {result.responses.map((response, index) => (
                                <div key={index} className="rs-card p-4">
                                    <AIResponse response={response} />
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
        </div>
    );
}
